# Generated by Django 4.2.2 on 2023-07-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waiting_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingListField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Field name')),
                ('section', models.CharField(choices=[('address', 'Address'), ('contact', 'Contact'), ('about', 'About you'), ('motivation', 'Motivation'), ('other', 'Other')], default='other', verbose_name='Section')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('type', models.CharField(choices=[('text', 'Text field'), ('textarea', 'Long text field'), ('integer', 'Integer field'), ('select', 'Dropdown field'), ('date', 'Date field'), ('url', 'URL field'), ('email', 'Email field'), ('phone', 'Phone field'), ('checkbox', 'Checkbox field'), ('radio', 'Radio button field')], default='text', max_length=255, verbose_name='Field type')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Label')),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True, verbose_name='Placeholder')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Data')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is required?')),
                ('is_displayed', models.BooleanField(default=False, verbose_name='Is displayed?')),
                ('waiting_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='waiting_list.waitinglist')),
            ],
        ),
    ]
