# Generated by Django 4.2.2 on 2023-07-27 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_list_field', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitinglistfield',
            options={'verbose_name': 'waiting list field', 'verbose_name_plural': 'waiting list fields'},
        ),
    ]
