# Generated by Django 4.2.2 on 2023-07-27 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationuser',
            options={'verbose_name': 'organisation user', 'verbose_name_plural': 'organisation users'},
        ),
    ]
