# Generated by Django 4.2.2 on 2023-07-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_token', '0003_authtoken_created_date_authtoken_used_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(max_length=100, verbose_name='Authentication token'),
        ),
    ]
