# Generated by Django 4.2.2 on 2023-07-27 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_token', '0004_alter_authtoken_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authtoken',
            options={'verbose_name': 'login token ', 'verbose_name_plural': 'login tokens'},
        ),
    ]
