version: '3'

services:
  backend:
    image: fairq:latest
    ports:
      - '8001:8000'
    env_file:
      - ./envs/dev.env
      - ./envs/secrets.env
    volumes:
      - ./backend:/backend
    command: "sh /scripts/dev.sh"
    depends_on:
      - postgres

  queue:
    image: fairq:latest
    env_file:
      - ./envs/dev.env
      - ./envs/secrets.env
    volumes:
      - ./backend:/backend
    command: "python manage.py qcluster"
    depends_on:
      - backend

  postgres:
    image: postgres:alpine3.18
    ports:
      - "5555:5432"
    env_file:
      - ./envs/dev.env
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
