name: fairq
dependencies:
  - python=3.11.3
  - pip=23.1.2
  - psycopg2
  - pip:
      - django==4.2.2
      - djangorestframework==3.14.0
      - djangorestframework_simplejwt==5.2.2
      - drf-yasg==1.21.5
      - pillow==9.5.0
      - flake8==6.0.0
      - gunicorn==20.1.0
      - sendgrid==6.10.0
      - django-cors-headers==4.1.0
      - django-countries==7.5.1
      - django-colorfield==0.9.0
      - django-q==1.3.9
      - phonenumbers==8.13.16
      - django-model-utils==4.3.1
      - django-singleton-model==0.2.3
