# Generated by Django 4.2.2 on 2023-07-13 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_user', '0001_initial'),
        ('membership', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_membership', to='organisation_user.organisationuser', verbose_name='User'),
        ),
    ]
