# Generated by Django 4.2.2 on 2023-07-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_membership_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.IntegerField(choices=[(1, 'Viewer'), (2, 'Administrator'), (3, 'Owner')], default=1, verbose_name='Role'),
        ),
    ]
