# Generated by Django 4.2.2 on 2023-07-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0001_initial'),
        ('waiting_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(verbose_name='Reconfirmation deadline')),
                ('first_reminder', models.DateTimeField(verbose_name='Reconfirmation first reminder date')),
                ('second_reminder', models.DateTimeField(verbose_name='Reconfirmation second reminder date')),
                ('reconfirmation_date', models.DateTimeField(blank=True, null=True, verbose_name='Reconfirmation date')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconfirmations', to='applicant.application', verbose_name='Application')),
                ('waiting_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconfirmations', to='waiting_list.waitinglist', verbose_name='Waiting list')),
            ],
        ),
    ]
