# Generated by Django 4.2.2 on 2023-07-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconfirmation', '0002_alter_reconfirmation_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconfirmation',
            name='first_reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reconfirmation first reminder date'),
        ),
        migrations.AlterField(
            model_name='reconfirmation',
            name='second_reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reconfirmation second reminder date'),
        ),
    ]
