# Generated by Django 4.2.2 on 2023-07-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconfirmation', '0004_alter_reconfirmation_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconfirmation',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='Reconfirmation deadline'),
        ),
        migrations.AlterField(
            model_name='reconfirmation',
            name='first_reminder',
            field=models.DateTimeField(null=True, verbose_name='Reconfirmation first reminder date'),
        ),
    ]
