# Generated by Django 4.2.2 on 2023-07-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0004_alter_identityverification_verified_by'),
        ('membership', '0003_alter_membership_member'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganisationUser',
        ),
    ]
