# Generated by Django 4.2.2 on 2023-07-13 14:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('usual_waiting_time', models.CharField(blank=True, max_length=255, verbose_name='Usual waiting time')),
                ('reconfirmation_cycle', models.IntegerField(choices=[(0, 'Never'), (1, 'Every month'), (2, 'Every 2 months'), (3, 'Every 3 months'), (6, 'Every 6 months'), (9, 'Every 9 months'), (12, 'Every 12 months'), (24, 'Every 2 years'), (36, 'Every 3 years')], default=0, verbose_name='Reconfirmation Cycle')),
                ('reconfirmation_first_reminder', models.IntegerField(choices=[(0, 'Do not remind'), (1, 'One day'), (2, 'Two days'), (7, 'One week'), (14, 'Two weeks'), (30, 'One month'), (60, 'Two months'), (90, 'Three months')], default=0, verbose_name='Reconfirmation First Reminder')),
                ('reconfirmation_second_reminder', models.IntegerField(choices=[(0, 'Do not remind'), (1, 'One day'), (2, 'Two days'), (7, 'One week'), (14, 'Two weeks'), (30, 'One month'), (60, 'Two months'), (90, 'Three months')], default=0, verbose_name='Reconfirmation Second Reminder')),
                ('reconfirmation_message', models.TextField(blank=True, verbose_name='Reconfirmation Message')),
                ('reconfirmation_remove', models.BooleanField(default=False, verbose_name='Reconfirmation Status')),
                ('num_selectable', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Number of Selectable applicants')),
                ('prioritization_sorting', models.CharField(choices=[('oldest_first', 'Oldest first'), ('random', 'Random')], default='oldest_first', max_length=255)),
                ('see_absolute_position', models.BooleanField(default=False, verbose_name='Show absolute position?')),
                ('see_relative_position', models.BooleanField(default=False, verbose_name='Show relative position?')),
                ('see_calculated_waiting_time', models.BooleanField(default=False, verbose_name='Show calculated waiting time?')),
                ('notify_applicant_monthly', models.BooleanField(default=False, verbose_name='Send notifications about the applicants monthly?')),
                ('notify_org_weekly', models.BooleanField(default=False, verbose_name='Send weekly organisation notification?')),
                ('notify_org_no_reconfirm', models.BooleanField(default=False, verbose_name='Send monthly organisation notification?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_organisation', to='organisation.organisation', verbose_name='Organisation')),
            ],
        ),
    ]
