# Generated by Django 4.2.2 on 2023-07-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='identity_verification_required',
            field=models.BooleanField(default=False, verbose_name='Require Identity Verification'),
        ),
    ]
