# Generated by Django 4.2.2 on 2023-07-22 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_remove_organisation_default_branding_and_more'),
        ('waiting_list', '0002_waitinglist_identity_verification_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_lists', to='organisation.organisation', verbose_name='Organisation'),
        ),
    ]
