# Generated by Django 4.2.2 on 2023-07-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_list', '0003_alter_waitinglist_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='slug',
            field=models.CharField(error_messages={'unique': 'This slug is already taken.'}, max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
