# Generated by Django 4.2.2 on 2023-07-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('activity', models.CharField(choices=[('edit', 'edited'), ('apply', 'applied'), ('team_join', 'joined'), ('team_invite', 'invited'), ('team_remove', 'removed'), ('do_something', 'did something')], default='do_something', max_length=255, verbose_name='Activity')),
                ('note', models.TextField(blank=True, verbose_name='Activity note')),
            ],
        ),
    ]
