# Generated by Django 4.2.2 on 2023-07-13 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0001_initial'),
        ('waiting_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='User activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='waiting_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_activity', to='waiting_list.waitinglist', verbose_name='Waiting list activity'),
        ),
    ]
