# Generated by Django 4.2.2 on 2023-07-25 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0006_application_estimated_selection_date'),
        ('waiting_list', '0004_alter_waitinglist_slug'),
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='application.application', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='waiting_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='waiting_list.waitinglist', verbose_name='Waiting list'),
        ),
    ]
