# Generated by Django 4.2.2 on 2023-07-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activity_application_alter_activity_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(choices=[('edit', 'edited'), ('apply', 'applied'), ('team_join', 'joined'), ('team_invite', 'invited'), ('team_remove', 'removed'), ('change_status', 'changed the status'), ('do_something', 'did something'), ('recalculate_positions', 'recalculated positions'), ('verify', 'verified the identity'), ('reconfirmed', 'reconfirmed their interest')], default='do_something', max_length=255, verbose_name='Activity'),
        ),
    ]
