# Generated by Django 4.2.2 on 2023-07-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activity_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(choices=[('edit', 'edited'), ('apply', 'applied'), ('team_join', 'joined'), ('team_invite', 'invited'), ('team_remove', 'removed'), ('change_status', 'changed the status'), ('do_something', 'did something'), ('recalculate_positions', 'recalculated positions'), ('verify', 'verified the identity'), ('reconfirmed', 'reconfirmed their interest'), ('edit_list', 'edited waiting list')], default='do_something', max_length=255, verbose_name='Activity'),
        ),
    ]
