# Generated by Django 4.2.2 on 2023-07-13 14:17

from django.db import migrations, models
import django.db.models.deletion
import identity_verification.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_front', models.FileField(max_length=254, upload_to=identity_verification.models.file_path, verbose_name='Front side')),
                ('file_back', models.FileField(blank=True, max_length=254, null=True, upload_to=identity_verification.models.file_path, verbose_name='Back side')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Identity verified')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='applicant.application', verbose_name='Application')),
            ],
        ),
    ]
