# Generated by Django 4.2.2 on 2023-07-20 17:36

from django.db import migrations, models
import django.db.models.deletion
import identity_verification.models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_delete_application'),
        ('identity_verification', '0004_alter_identityverification_verified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityverification',
            name='application',
        ),
        migrations.AddField(
            model_name='identityverification',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='applicant.applicant', verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiry date'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('verified', 'verified'), ('declined', 'declined'), ('expired', 'expired')], default='pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='file_back',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=identity_verification.models.file_path, verbose_name='Back side'),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='file_front',
            field=models.ImageField(max_length=254, upload_to=identity_verification.models.file_path, verbose_name='Front side'),
        ),
    ]
