# Generated by Django 4.2.2 on 2023-07-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0007_alter_identityverification_file_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiry date'),
        ),
    ]
