# Generated by Django 4.2.2 on 2023-07-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0008_identityverification_verification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityverification',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verification date'),
        ),
    ]
