# Generated by Django 4.2.2 on 2023-07-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0009_alter_identityverification_verification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
