# Generated by Django 4.2.2 on 2023-07-28 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_alter_applicant_options'),
        ('identity_verification', '0012_alter_identityverification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identityverification',
            options={'verbose_name': 'identity verification document', 'verbose_name_plural': 'identity verification documents'},
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='applicant.applicant', verbose_name='Applicant'),
        ),
    ]
