# Generated by Django 4.2.2 on 2023-07-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0001_initial'),
        ('waiting_list_field', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(verbose_name='Application field value')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_fields', to='applicant.application', verbose_name='Application')),
                ('waiting_list_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_field', to='waiting_list_field.waitinglistfield', verbose_name='Waiting list field')),
            ],
        ),
    ]
