# Generated by Django 4.2.2 on 2023-07-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('application_field', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfield',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_fields', to='application.application', verbose_name='Application'),
        ),
    ]
