# Generated by Django 4.2.2 on 2023-07-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_field', '0002_alter_applicationfield_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfield',
            name='value',
            field=models.TextField(verbose_name='Application field value'),
        ),
    ]
