# Generated by Django 4.2.2 on 2023-07-27 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_field', '0004_alter_applicationfield_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationfield',
            options={'verbose_name': 'application field', 'verbose_name_plural': 'application fields'},
        ),
    ]
