# Generated by Django 4.2.2 on 2023-07-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_application_last_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Waiting position'),
        ),
    ]
