# Generated by Django 4.2.2 on 2023-07-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='waiting_since_date',
            field=models.DateTimeField(null=True, verbose_name='Waiting since date'),
        ),
    ]
