# Generated by Django 4.2.2 on 2023-07-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_application_waiting_since_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='selected_date',
            field=models.DateTimeField(null=True, verbose_name='Selected date'),
        ),
    ]
