# Generated by Django 4.2.2 on 2023-07-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_application_selected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='estimated_selection_date',
            field=models.DateTimeField(null=True, verbose_name='Estimated projected selection date'),
        ),
    ]
