# Generated by Django 4.2.2 on 2023-07-27 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_application_estimated_selection_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'application', 'verbose_name_plural': 'applications'},
        ),
    ]
