# Generated by Django 4.2.2 on 2023-07-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waiting_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'created'), ('waiting', 'waiting'), ('selected', 'selected'), ('removed', 'removed')], default='created', max_length=50, verbose_name='Applicant status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('last_login_date', models.DateTimeField(blank=True, null=True, verbose_name='Last login')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applicant.applicant', verbose_name='Applicant')),
                ('waiting_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='waiting_list.waitinglist', verbose_name='Waiting list')),
            ],
        ),
    ]
