# Generated by Django 4.2.2 on 2023-07-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='application',
            name='waiting_list',
        ),
    ]
