# Generated by Django 4.2.2 on 2023-07-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_field', '0002_alter_applicationfield_application'),
        ('reconfirmation', '0002_alter_reconfirmation_application'),
        ('applicant', '0003_remove_application_applicant_and_more'),
        ('identity_verification', '0003_alter_identityverification_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
