# Generated by Django 4.2.2 on 2023-07-13 14:17

import colorfield.fields
from django.db import migrations, models
import organisation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Organisation name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Organisation description')),
                ('website_url', models.URLField(blank=True, max_length=255, verbose_name='Website')),
                ('contact_url', models.URLField(blank=True, max_length=255, verbose_name='Contact Website')),
                ('privacy_url', models.URLField(blank=True, max_length=255, verbose_name='Privacy Website')),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to=organisation.models.logo_file_path, verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, max_length=255, null=True, upload_to=organisation.models.banner_file_path, verbose_name='Banner')),
                ('font', models.CharField(choices=[('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('Times New Roman', 'Times New Roman'), ('Courier New', 'Courier New'), ('Verdana', 'Verdana'), ('Georgia', 'Georgia'), ('Palatino', 'Palatino'), ('Garamond', 'Garamond'), ('Bookman', 'Bookman'), ('Avant Garde', 'Avant Garde'), ('Comic Sans MS', 'Comic Sans MS'), ('Trebuchet MS', 'Trebuchet MS'), ('Arial Black', 'Arial Black'), ('Impact', 'Impact')], default='Arial', max_length=100, verbose_name='Font type')),
                ('background_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Background color')),
                ('font_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None, verbose_name='Font color')),
                ('accent_color', colorfield.fields.ColorField(default='#0000FF', image_field=None, max_length=18, samples=None, verbose_name='Accent color')),
                ('default_branding', models.BooleanField(default=1, verbose_name='Default branding?')),
            ],
        ),
    ]
