# Generated by Django 4.2.2 on 2023-07-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='default_branding',
        ),
        migrations.AddField(
            model_name='organisation',
            name='custom_branding',
            field=models.BooleanField(default=False, verbose_name='Enable custom branding?'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='remove_default_branding',
            field=models.BooleanField(default=False, verbose_name='Remove fairQ branding?'),
        ),
    ]
