# Generated by Django 4.2.2 on 2023-07-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_remove_organisation_default_branding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='font',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Helvetica', 'Helvetica'), ('Verdana', 'Verdana'), ('Trebuchet MS', 'Trebuchet MS'), ('Geneva', 'Geneva'), ('Roboto', 'Roboto'), ('Times New Roman', 'Times New Roman'), ('Georgia', 'Georgia'), ('Palatino Linotype', 'Palatino Linotype'), ('Courier New', 'Courier New')], default='Arial', max_length=100, verbose_name='Font type'),
        ),
    ]
