# Generated by Django 4.2.2 on 2023-07-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='catch_emails',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='catch_all_email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='catch_all_emails_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
