# Generated by Django 4.2.2 on 2023-07-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_remove_siteconfiguration_catch_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='catch_all_email_address',
            field=models.EmailField(default=True, max_length=254, verbose_name='Shared address to catch emails.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='catch_all_emails_enabled',
            field=models.BooleanField(default=False, verbose_name='Catch all emails and send to a shared address.'),
        ),
    ]
