# Generated by Django 4.2.2 on 2023-07-25 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waiting_list', '0004_alter_waitinglist_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_people', models.IntegerField(verbose_name='Total People')),
                ('new_people', models.IntegerField(verbose_name='New People')),
                ('withdrawn_people', models.IntegerField(verbose_name='Withdrawn People')),
                ('dropped_out_people', models.IntegerField(verbose_name='Dropped Out People')),
                ('selected_people', models.IntegerField(verbose_name='Selected People')),
                ('estimated_time_for_new_applicants', models.IntegerField(verbose_name='Estimated Time for New Applicants')),
                ('average_waiting_time_for_selected_people', models.IntegerField(verbose_name='Average Waiting Time for Selected People')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('waiting_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='waiting_list.waitinglist', verbose_name='Waiting List')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
