# Generated by Django 4.2.2 on 2023-07-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='average_waiting_time_for_selected_people',
            field=models.IntegerField(null=True, verbose_name='Average Waiting Time for Selected People'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='estimated_time_for_new_applicants',
            field=models.IntegerField(null=True, verbose_name='Estimated Time for New Applicants'),
        ),
    ]
