# Generated by Django 4.2.2 on 2023-07-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_list', '0004_alter_waitinglist_slug'),
        ('stats', '0002_alter_stats_average_waiting_time_for_selected_people_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_people', models.IntegerField()),
                ('new_people', models.IntegerField()),
                ('new_withdrawn_people', models.IntegerField()),
                ('dropped_out_people', models.IntegerField()),
                ('selected_people', models.IntegerField()),
                ('estimated_time_for_new_applicants', models.IntegerField(blank=True, null=True)),
                ('average_waiting_time_for_selected_people', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Stats',
            new_name='WaitingListStats',
        ),
    ]
