# Generated by Django 4.2.2 on 2023-07-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_alter_overallstats_average_waiting_time_for_selected_people_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overallstats',
            old_name='dropped_out_people',
            new_name='removed_people',
        ),
        migrations.RenameField(
            model_name='waitingliststats',
            old_name='dropped_out_people',
            new_name='removed_people',
        ),
        migrations.RemoveField(
            model_name='overallstats',
            name='new_withdrawn_people',
        ),
        migrations.RemoveField(
            model_name='waitingliststats',
            name='withdrawn_people',
        ),
    ]
