# Generated by Django 4.2.2 on 2023-07-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_rename_dropped_out_people_overallstats_removed_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallstats',
            name='age_0_18',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age 0-18'),
        ),
        migrations.AddField(
            model_name='overallstats',
            name='age_19_25',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age 19-25'),
        ),
        migrations.AddField(
            model_name='overallstats',
            name='age_26_35',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age 26-35'),
        ),
        migrations.AddField(
            model_name='overallstats',
            name='age_36_50',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age 36-50'),
        ),
        migrations.AddField(
            model_name='overallstats',
            name='age_51_65',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age 51-65'),
        ),
        migrations.AddField(
            model_name='overallstats',
            name='age_65_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age 65+'),
        ),
        migrations.AddField(
            model_name='overallstats',
            name='female_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Female Count'),
        ),
        migrations.AddField(
            model_name='overallstats',
            name='male_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Male Count'),
        ),
        migrations.AddField(
            model_name='overallstats',
            name='other_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Other Count'),
        ),
        migrations.AddField(
            model_name='waitingliststats',
            name='age_0_18',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age 0-18'),
        ),
        migrations.AddField(
            model_name='waitingliststats',
            name='age_19_25',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age 19-25'),
        ),
        migrations.AddField(
            model_name='waitingliststats',
            name='age_26_35',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age 26-35'),
        ),
        migrations.AddField(
            model_name='waitingliststats',
            name='age_36_50',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age 36-50'),
        ),
        migrations.AddField(
            model_name='waitingliststats',
            name='age_51_65',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age 51-65'),
        ),
        migrations.AddField(
            model_name='waitingliststats',
            name='age_65_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age 65+'),
        ),
        migrations.AddField(
            model_name='waitingliststats',
            name='female_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Female Count'),
        ),
        migrations.AddField(
            model_name='waitingliststats',
            name='male_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Male Count'),
        ),
        migrations.AddField(
            model_name='waitingliststats',
            name='other_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Other Count'),
        ),
    ]
