# Generated by Django 4.2.2 on 2023-07-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_list', '0005_alter_waitinglist_options'),
        ('stats', '0008_alter_waitingliststats_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatsPerWaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_applicants', models.IntegerField(verbose_name='Total Applicants')),
                ('new_applicants', models.IntegerField(null=True, verbose_name='New Applicants')),
                ('removed_applicants', models.IntegerField(null=True, verbose_name='Removed Applicants')),
                ('selected_applicants', models.IntegerField(null=True, verbose_name='Selected Applicants')),
                ('estimated_time_for_new_applicants', models.IntegerField(null=True, verbose_name='Estimated Time for New Applicants')),
                ('average_waiting_time_for_selected_people', models.IntegerField(null=True, verbose_name='Average Waiting Time for Selected People')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('age_0_18', models.IntegerField(blank=True, null=True, verbose_name='Age 0-18')),
                ('age_19_25', models.IntegerField(blank=True, null=True, verbose_name='Age 19-25')),
                ('age_26_35', models.IntegerField(blank=True, null=True, verbose_name='Age 26-35')),
                ('age_36_50', models.IntegerField(blank=True, null=True, verbose_name='Age 36-50')),
                ('age_51_65', models.IntegerField(blank=True, null=True, verbose_name='Age 51-65')),
                ('age_65_plus', models.IntegerField(blank=True, null=True, verbose_name='Age 65+')),
                ('male_count', models.IntegerField(blank=True, null=True, verbose_name='Male Count')),
                ('female_count', models.IntegerField(blank=True, null=True, verbose_name='Female Count')),
                ('other_count', models.IntegerField(blank=True, null=True, verbose_name='Other Count')),
                ('waiting_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='waiting_list.waitinglist', verbose_name='Waiting List')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
            },
        ),
        migrations.DeleteModel(
            name='OverallStats',
        ),
        migrations.DeleteModel(
            name='WaitingListStats',
        ),
    ]
