# Generated by Django 4.2.2 on 2023-07-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_dailystatsperwaitinglist_delete_overallstats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailystatsperwaitinglist',
            old_name='average_waiting_time_for_selected_people',
            new_name='average_waiting_time_for_selected_applicants',
        ),
    ]
