# Generated by Django 4.2.2 on 2023-07-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_rename_average_waiting_time_for_selected_people_dailystatsperwaitinglist_average_waiting_time_for_se'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatsperwaitinglist',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
