# Generated by Django 4.2.2 on 2023-07-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_alter_dailystatsperwaitinglist_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystatsperwaitinglist',
            name='average_waiting_time_for_selected_applicants',
        ),
        migrations.RemoveField(
            model_name='dailystatsperwaitinglist',
            name='estimated_time_for_new_applicants',
        ),
        migrations.RemoveField(
            model_name='dailystatsperwaitinglist',
            name='removed_applicants',
        ),
        migrations.RemoveField(
            model_name='dailystatsperwaitinglist',
            name='selected_applicants',
        ),
        migrations.AddField(
            model_name='dailystatsperwaitinglist',
            name='average_current_waiting_time',
            field=models.IntegerField(null=True, verbose_name='Average waiting time of currently waiting applicants'),
        ),
        migrations.AddField(
            model_name='dailystatsperwaitinglist',
            name='average_waiting_time_of_selected_applicants',
            field=models.IntegerField(null=True, verbose_name='Average waiting time of already selected applicants'),
        ),
        migrations.AddField(
            model_name='dailystatsperwaitinglist',
            name='new_selected',
            field=models.IntegerField(null=True, verbose_name='Newly Selected Applicants'),
        ),
        migrations.AddField(
            model_name='dailystatsperwaitinglist',
            name='total_pending',
            field=models.IntegerField(default=1, verbose_name='Total Pending'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailystatsperwaitinglist',
            name='total_removed',
            field=models.IntegerField(default=1, verbose_name='Total Removed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailystatsperwaitinglist',
            name='total_selected',
            field=models.IntegerField(default=1, verbose_name='Total Selected'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailystatsperwaitinglist',
            name='total_waiting',
            field=models.IntegerField(default=1, verbose_name='Total Waiting'),
            preserve_default=False,
        ),
    ]
