# Generated by Django 4.2.2 on 2023-07-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_remove_dailystatsperwaitinglist_average_waiting_time_for_selected_applicants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatsperwaitinglist',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
