# Generated by Django 4.2.2 on 2023-07-28 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_remove_dailystatsperwaitinglist_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystatsperwaitinglist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 8, 48, 1, 634781, tzinfo=datetime.timezone.utc), verbose_name='Date'),
            preserve_default=False,
        ),
    ]
